import { ContactProperty } from '@/components/types';
export const contactProperties: ContactProperty[] = [
  {
    name: 'First Name',
    type: 'singleLineString',
    id: 'firstName',
    isRequired: true,
    isSearchable: true,
  },
  {
    name: 'Last Name',
    type: 'singleLineString',
    id: 'lastName',
    isRequired: true,
    isSearchable: true,
  },
  {
    name: 'Work Phone',
    type: 'phoneNumber',
    id: 'workPhone',
    isRequired: true,
    isSearchable: true,
  },
  {
    name: 'Personal Phone',
    type: 'phoneNumber',
    id: 'cellPhone',
    isRequired: true,
    isSearchable: true,
  },
  {
    name: 'Work Address',
    type: 'singleLineString',
    id: 'workAddress',
    isRequired: true,
    isSearchable: false,
    isCustomizedField: true,
  },
  {
    name: 'Work Email',
    type: 'email',
    id: 'workEmail',
    isRequired: false,
    isSearchable: true,
  },
  {
    name: 'Personal Email',
    type: 'email',
    id: 'email',
    isRequired: false,
    isSearchable: true,
  },
  {
    name: 'Categories',
    type: 'singleLineString',
    id: 'categories',
    isRequired: true,
    isSearchable: true,
    isCustomizedField: true,
  },
  {
    name: 'Notes',
    type: 'multiLineString',
    id: 'note',
    isRequired: false,
    isSearchable: true,
  },
  {
    name: 'Organisation Name',
    type: 'singleLineString',
    id: 'organization',
    isRequired: false,
    isSearchable: false,
  },
  {
    name: 'WebSite Url',
    type: 'url',
    id: 'url',
    isRequired: false,
    isSearchable: true,
  },
  {
    name: 'Tags',
    type: 'tag',
    id: 'tags',
    isRequired: false,
    isSearchable: false,
    isCustomizedField: true,
  },
];
